services:
  - type: web
    name: theme-switcher
    env: static
    buildCommand: |
      npm ci
      chmod +x ./node_modules/.bin/react-scripts
      CI=false npm run build
    publishDir: build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 16
      - key: NODE_ENV
        value: production
      - key: CI
        value: false
      - key: SKIP_PREFLIGHT_CHECK
        value: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
